### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by LifeCANvs** [IanGuim/clone-disk#1]
Hi, what license applies to this script?

**Comment by IanGuim** [comment]
> Hi, what license applies to this script?

Fixed! Since dc3dd uses GPLv2, I'll keep the same license.

**Comment by LifeCANvs** [comment]
> > Hi, what license applies to this script?
> 
> Fixed! Since dc3dd uses GPLv2, I'll keep the same license.

Thanks for the clarification.
